commit
tigerscave/falcon-scheme-dojo pull request #11
Opened 2021-10-09 14:31 UTC by falconkun

手習い2～3章前半

2021-10-13 11:41 UTC, hrl7 commented on cp2/prac01.scm
> +
2行以上の空白行はだいたい意味がないので1行にしよう

2022-09-17 01:22 UTC, azamiya requested changes

2022-09-17 01:22 UTC, azamiya commented on practice/0903.scm
> +  (cond
インデント二行あけましょう

```
(define sum
  (lambda (l)
    (cond

```

2022-09-17 01:22 UTC, azamiya commented on practice/0903.scm
> +  (+ 1 n)))
インデント

2022-09-17 01:22 UTC, azamiya commented on practice/0903.scm
> +  (cond
インデント

2022-09-17 01:22 UTC, azamiya commented on practice/0903.scm
> +  (cond
インデント

2022-09-17 01:22 UTC, azamiya commented on practice/0903.scm
> +  (cond
インデント

2022-09-17 01:22 UTC, azamiya commented on practice/0903.scm
> +  (cond
インデント

2022-09-17 01:29 UTC, merged